//////////////////////////////////////////////////////////
////////// GENERATED BY RADIANT FIRE LOADER //////////////
//////////////////////////////////////////////////////////


if (strcmp(token.value, "Nome") == 0) {
	return APE_TOKEN_NOME_ID;
}

if (strcmp(token.value, "(") == 0) {
	return APE_TOKEN_ABRE_PARENTESES_ID;
}

if (strcmp(token.value, "do") == 0) {
	return APE_TOKEN_DO_ID;
}

if (strcmp(token.value, "while") == 0) {
	return APE_TOKEN_WHILE_ID;
}

if (strcmp(token.value, "repeat") == 0) {
	return APE_TOKEN_REPEAT_ID;
}

if (strcmp(token.value, "if") == 0) {
	return APE_TOKEN_IF_ID;
}

if (strcmp(token.value, "for") == 0) {
	return APE_TOKEN_FOR_ID;
}

if (strcmp(token.value, "function") == 0) {
	return APE_TOKEN_FUNCTION_ID;
}

if (strcmp(token.value, "local") == 0) {
	return APE_TOKEN_LOCAL_ID;
}

if (strcmp(token.value, "return") == 0) {
	return APE_TOKEN_RETURN_ID;
}

if (strcmp(token.value, "break") == 0) {
	return APE_TOKEN_BREAK_ID;
}

if (strcmp(token.value, "[") == 0) {
	return APE_TOKEN_ABRE_COLCHETES_ID;
}

if (strcmp(token.value, ".") == 0) {
	return APE_TOKEN_PONTO_ID;
}

if (strcmp(token.value, ",") == 0) {
	return APE_TOKEN_VIRGULA_ID;
}

if (strcmp(token.value, "{") == 0) {
	return APE_TOKEN_ABRE_CHAVES_ID;
}

if (strcmp(token.value, "=") == 0) {
	return APE_TOKEN_IGUAL_ID;
}

if (strcmp(token.value, "Cadeia") == 0) {
	return APE_TOKEN_CADEIA_ID;
}

if (strcmp(token.value, ":") == 0) {
	return APE_TOKEN_DOIS_PONTOS_ID;
}

if (strcmp(token.value, ";") == 0) {
	return APE_TOKEN_PONTO_E_VIRGULA_ID;
}

if (strcmp(token.value, ")") == 0) {
	return APE_TOKEN_FECHA_PARENTESES_ID;
}

if (strcmp(token.value, "}") == 0) {
	return APE_TOKEN_FECHA_CHAVES_ID;
}

if (strcmp(token.value, "...") == 0) {
	return APE_TOKEN_PONTO_PONTO_PONTO_ID;
}

if (strcmp(token.value, "end") == 0) {
	return APE_TOKEN_END_ID;
}

if (strcmp(token.value, "]") == 0) {
	return APE_TOKEN_FECHA_COLCHETES_ID;
}

if (strcmp(token.value, "in") == 0) {
	return APE_TOKEN_IN_ID;
}

if (strcmp(token.value, "then") == 0) {
	return APE_TOKEN_THEN_ID;
}

if (strcmp(token.value, "elseif") == 0) {
	return APE_TOKEN_ELSEIF_ID;
}

if (strcmp(token.value, "else") == 0) {
	return APE_TOKEN_ELSE_ID;
}

if (strcmp(token.value, "until") == 0) {
	return APE_TOKEN_UNTIL_ID;
}

if (strcmp(token.value, "nil") == 0) {
	return APE_TOKEN_NIL_ID;
}

if (strcmp(token.value, "false") == 0) {
	return APE_TOKEN_FALSE_ID;
}

if (strcmp(token.value, "true") == 0) {
	return APE_TOKEN_TRUE_ID;
}

if (strcmp(token.value, "Numero") == 0) {
	return APE_TOKEN_NUMERO_ID;
}

if (strcmp(token.value, "-") == 0) {
	return APE_TOKEN_SUBTRACAO_ID;
}

if (strcmp(token.value, "not") == 0) {
	return APE_TOKEN_NOT_ID;
}

if (strcmp(token.value, "#") == 0) {
	return APE_TOKEN_JOGO_DA_VELHA_ID;
}

if (strcmp(token.value, "+") == 0) {
	return APE_TOKEN_SOMA_ID;
}

if (strcmp(token.value, "*") == 0) {
	return APE_TOKEN_MULTIPLICACAO_ID;
}

if (strcmp(token.value, "/") == 0) {
	return APE_TOKEN_DIVISAO_ID;
}

if (strcmp(token.value, "^") == 0) {
	return APE_TOKEN_ACENTO_CIRCUNFLEXO_ID;
}

if (strcmp(token.value, "%") == 0) {
	return APE_TOKEN_PORCENTAGEM_ID;
}

if (strcmp(token.value, "..") == 0) {
	return APE_TOKEN_PONTO_PONTO_ID;
}

if (strcmp(token.value, "<") == 0) {
	return APE_TOKEN_MENOR_ID;
}

if (strcmp(token.value, "<=") == 0) {
	return APE_TOKEN_MENOR_IGUAL_ID;
}

if (strcmp(token.value, ">") == 0) {
	return APE_TOKEN_MAIOR_ID;
}

if (strcmp(token.value, ">=") == 0) {
	return APE_TOKEN_MAIOR_IGUAL_ID;
}

if (strcmp(token.value, "==") == 0) {
	return APE_TOKEN_IGUAL_IGUAL_ID;
}

if (strcmp(token.value, "~=") == 0) {
	return APE_TOKEN_TIO_IGUAL_ID;
}

if (strcmp(token.value, "and") == 0) {
	return APE_TOKEN_AND_ID;
}

if (strcmp(token.value, "or") == 0) {
	return APE_TOKEN_OR_ID;
}

//////////////////////////////////////////////////////////