//////////////////////////////////////////////////////////
////////// GENERATED BY RADIANT FIRE LOADER //////////////
//////////////////////////////////////////////////////////

#define		APE_TOTAL_MACHINES		2

/* ape invalid transition */
#define		APE_INVALID_STATE		-1

/* ape machine ids */
#define		APE_MACHINE_BLOCO_ID		0
#define		APE_MACHINE_EXP_ID		1

/* ape tokens ids */
#define		APE_TOKEN_NOME_ID		0
#define		APE_TOKEN_ABRE_PARENTESES_ID		1
#define		APE_TOKEN_DO_ID		2
#define		APE_TOKEN_WHILE_ID		3
#define		APE_TOKEN_REPEAT_ID		4
#define		APE_TOKEN_IF_ID		5
#define		APE_TOKEN_FOR_ID		6
#define		APE_TOKEN_FUNCTION_ID		7
#define		APE_TOKEN_LOCAL_ID		8
#define		APE_TOKEN_RETURN_ID		9
#define		APE_TOKEN_BREAK_ID		10
#define		APE_TOKEN_ABRE_COLCHETES_ID		11
#define		APE_TOKEN_PONTO_ID		12
#define		APE_TOKEN_VIRGULA_ID		13
#define		APE_TOKEN_ABRE_CHAVES_ID		14
#define		APE_TOKEN_IGUAL_ID		15
#define		APE_TOKEN_CADEIA_ID		16
#define		APE_TOKEN_DOIS_PONTOS_ID		17
#define		APE_TOKEN_PONTO_E_VIRGULA_ID		18
#define		APE_TOKEN_FECHA_PARENTESES_ID		19
#define		APE_TOKEN_FECHA_CHAVES_ID		20
#define		APE_TOKEN_PONTO_PONTO_PONTO_ID		21
#define		APE_TOKEN_END_ID		22
#define		APE_TOKEN_FECHA_COLCHETES_ID		23
#define		APE_TOKEN_IN_ID		24
#define		APE_TOKEN_THEN_ID		25
#define		APE_TOKEN_ELSEIF_ID		26
#define		APE_TOKEN_ELSE_ID		27
#define		APE_TOKEN_UNTIL_ID		28
#define		APE_TOKEN_NIL_ID		29
#define		APE_TOKEN_FALSE_ID		30
#define		APE_TOKEN_TRUE_ID		31
#define		APE_TOKEN_NUMERO_ID		32
#define		APE_TOKEN_SUBTRACAO_ID		33
#define		APE_TOKEN_NOT_ID		34
#define		APE_TOKEN_JOGO_DA_VELHA_ID		35
#define		APE_TOKEN_SOMA_ID		36
#define		APE_TOKEN_MULTIPLICACAO_ID		37
#define		APE_TOKEN_DIVISAO_ID		38
#define		APE_TOKEN_ACENTO_CIRCUNFLEXO_ID		39
#define		APE_TOKEN_PORCENTAGEM_ID		40
#define		APE_TOKEN_PONTO_PONTO_ID		41
#define		APE_TOKEN_MENOR_ID		42
#define		APE_TOKEN_MENOR_IGUAL_ID		43
#define		APE_TOKEN_MAIOR_ID		44
#define		APE_TOKEN_MAIOR_IGUAL_ID		45
#define		APE_TOKEN_IGUAL_IGUAL_ID		46
#define		APE_TOKEN_TIO_IGUAL_ID		47
#define		APE_TOKEN_AND_ID		48
#define		APE_TOKEN_OR_ID		49

//////////////////////////////////////////////////////////