//////////////////////////////////////////////////////////
////////// GENERATED BY RADIANT FIRE LOADER //////////////
//////////////////////////////////////////////////////////

add(&table_reserved_words, "Nome");
add(&table_reserved_words, "(");
add(&table_reserved_words, "do");
add(&table_reserved_words, "while");
add(&table_reserved_words, "repeat");
add(&table_reserved_words, "if");
add(&table_reserved_words, "for");
add(&table_reserved_words, "function");
add(&table_reserved_words, "local");
add(&table_reserved_words, "return");
add(&table_reserved_words, "break");
add(&table_reserved_words, "[");
add(&table_reserved_words, ".");
add(&table_reserved_words, ",");
add(&table_reserved_words, "{");
add(&table_reserved_words, "=");
add(&table_reserved_words, "Cadeia");
add(&table_reserved_words, ":");
add(&table_reserved_words, ";");
add(&table_reserved_words, ")");
add(&table_reserved_words, "}");
add(&table_reserved_words, "...");
add(&table_reserved_words, "end");
add(&table_reserved_words, "]");
add(&table_reserved_words, "in");
add(&table_reserved_words, "then");
add(&table_reserved_words, "elseif");
add(&table_reserved_words, "else");
add(&table_reserved_words, "until");
add(&table_reserved_words, "nil");
add(&table_reserved_words, "false");
add(&table_reserved_words, "true");
add(&table_reserved_words, "Numero");
add(&table_reserved_words, "-");
add(&table_reserved_words, "not");
add(&table_reserved_words, "#");
add(&table_reserved_words, "+");
add(&table_reserved_words, "*");
add(&table_reserved_words, "/");
add(&table_reserved_words, "^");
add(&table_reserved_words, "%");
add(&table_reserved_words, "..");
add(&table_reserved_words, "<");
add(&table_reserved_words, "<=");
add(&table_reserved_words, ">");
add(&table_reserved_words, ">=");
add(&table_reserved_words, "==");
add(&table_reserved_words, "~=");
add(&table_reserved_words, "and");
add(&table_reserved_words, "or");

//////////////////////////////////////////////////////////