//////////////////////////////////////////////////////////
////////// GENERATED BY RADIANT FIRE LOADER //////////////
//////////////////////////////////////////////////////////


if (strcmp(token->value, "functions")) {
	return APE_TOKEN_FUNCTIONS_ID;
}

if (strcmp(token->value, "int")) {
	return APE_TOKEN_INT_ID;
}

if (strcmp(token->value, "char")) {
	return APE_TOKEN_CHAR_ID;
}

if (strcmp(token->value, "boolean")) {
	return APE_TOKEN_BOOLEAN_ID;
}

if (strcmp(token->value, "void")) {
	return APE_TOKEN_VOID_ID;
}

if (strcmp(token->value, "main")) {
	return APE_TOKEN_MAIN_ID;
}

if (strcmp(token->value, "id")) {
	return APE_TOKEN_ID_ID;
}

if (strcmp(token->value, "{")) {
	return APE_TOKEN_ABRE_CHAVES_ID;
}

if (strcmp(token->value, "(")) {
	return APE_TOKEN_ABRE_PARENTESES_ID;
}

if (strcmp(token->value, ";")) {
	return APE_TOKEN_PONTO_E_VIRGULA_ID;
}

if (strcmp(token->value, "begin")) {
	return APE_TOKEN_BEGIN_ID;
}

if (strcmp(token->value, ")")) {
	return APE_TOKEN_FECHA_PARENTESES_ID;
}

if (strcmp(token->value, "}")) {
	return APE_TOKEN_FECHA_CHAVES_ID;
}

if (strcmp(token->value, "return")) {
	return APE_TOKEN_RETURN_ID;
}

if (strcmp(token->value, ",")) {
	return APE_TOKEN_VIRGULA_ID;
}

if (strcmp(token->value, "if")) {
	return APE_TOKEN_IF_ID;
}

if (strcmp(token->value, "while")) {
	return APE_TOKEN_WHILE_ID;
}

if (strcmp(token->value, "scan")) {
	return APE_TOKEN_SCAN_ID;
}

if (strcmp(token->value, "print")) {
	return APE_TOKEN_PRINT_ID;
}

if (strcmp(token->value, "=")) {
	return APE_TOKEN_IGUAL_ID;
}

if (strcmp(token->value, "string")) {
	return APE_TOKEN_STRING_ID;
}

if (strcmp(token->value, "+")) {
	return APE_TOKEN_SOMA_ID;
}

if (strcmp(token->value, "else")) {
	return APE_TOKEN_ELSE_ID;
}

if (strcmp(token->value, "inteiro")) {
	return APE_TOKEN_INTEIRO_ID;
}

if (strcmp(token->value, "*")) {
	return APE_TOKEN_MULTIPLICACAO_ID;
}

if (strcmp(token->value, "/")) {
	return APE_TOKEN_DIVISAO_ID;
}

if (strcmp(token->value, "-")) {
	return APE_TOKEN_SUBTRACAO_ID;
}

if (strcmp(token->value, "NOT")) {
	return APE_TOKEN_NOT_ID;
}

if (strcmp(token->value, "booleano")) {
	return APE_TOKEN_BOOLEANO_ID;
}

if (strcmp(token->value, "<")) {
	return APE_TOKEN_MENOR_ID;
}

if (strcmp(token->value, "<=")) {
	return APE_TOKEN_MENOR_IGUAL_ID;
}

if (strcmp(token->value, ">")) {
	return APE_TOKEN_MAIOR_ID;
}

if (strcmp(token->value, ">=")) {
	return APE_TOKEN_MAIOR_IGUAL_ID;
}

if (strcmp(token->value, "==")) {
	return APE_TOKEN_IGUAL_IGUAL_ID;
}

if (strcmp(token->value, "!=")) {
	return APE_TOKEN_DIFERENTE_ID;
}

if (strcmp(token->value, "AND")) {
	return APE_TOKEN_AND_ID;
}

if (strcmp(token->value, "OR")) {
	return APE_TOKEN_OR_ID;
}

//////////////////////////////////////////////////////////