//////////////////////////////////////////////////////////
////////// GENERATED BY RADIANT FIRE LOADER //////////////
//////////////////////////////////////////////////////////

add(&table_reserved_words, "functions");
add(&table_reserved_words, "int");
add(&table_reserved_words, "char");
add(&table_reserved_words, "boolean");
add(&table_reserved_words, "void");
add(&table_reserved_words, "main");
add(&table_reserved_words, "id");
add(&table_reserved_words, "{");
add(&table_reserved_words, "(");
add(&table_reserved_words, ";");
add(&table_reserved_words, "begin");
add(&table_reserved_words, ")");
add(&table_reserved_words, "}");
add(&table_reserved_words, "return");
add(&table_reserved_words, ",");
add(&table_reserved_words, "if");
add(&table_reserved_words, "while");
add(&table_reserved_words, "scan");
add(&table_reserved_words, "print");
add(&table_reserved_words, "=");
add(&table_reserved_words, "string");
add(&table_reserved_words, "+");
add(&table_reserved_words, "else");
add(&table_reserved_words, "inteiro");
add(&table_reserved_words, "*");
add(&table_reserved_words, "/");
add(&table_reserved_words, "-");
add(&table_reserved_words, "NOT");
add(&table_reserved_words, "booleano");
add(&table_reserved_words, "<");
add(&table_reserved_words, "<=");
add(&table_reserved_words, ">");
add(&table_reserved_words, ">=");
add(&table_reserved_words, "==");
add(&table_reserved_words, "!=");
add(&table_reserved_words, "AND");
add(&table_reserved_words, "OR");

//////////////////////////////////////////////////////////